### ISSUE TITLE
请问tls是基于标准库crypto/tls的那个版本改的

### ISSUE THREAD

**Issue by scf0220** [cetcxinlian/cryptogm#1]
请问https://github.com/cetcxinlian/cryptogm/tree/master/tls 这个代码是基于https://github.com/golang/go/tree/master/src/crypto/tls 的那个版本改的
谢谢

**Comment by qylixin** [comment]
> 请问https://github.com/cetcxinlian/cryptogm/tree/master/tls 这个代码是基于https://github.com/golang/go/tree/master/src/crypto/tls 的那个版本改的
> 谢谢

经过与go源码对比
x509 应该是基于go1.9.x
tls 是基于go1.11.x

**Comment by CollenSu** [comment]
> 经过与go源码对比
> x509 应该是基于go1.9.x
> tls 是基于go1.11.x

是这个版本
