### ISSUE TITLE
请问这边sm4的加密模式是CBC还是ECB的

### ISSUE THREAD

**Issue by smallbirdwy** [cetcxinlian/cryptogm#2]
请问这边sm4的加密模式是CBC还是ECB的

**Comment by cetcxinlian** [comment]
现在此库转移到https://github.com/Hyperledger-TWGC/ccs-gm。支持CBC和ECB两种模式。

**Comment by CollenSu** [comment]
现在此库转移到https://github.com/Hyperledger-TWGC/ccs-gm。支持CBC和ECB两种模式。

**Comment by CollenSu** [comment]
现在此库转移到https://github.com/Hyperledger-TWGC/ccs-gm。支持CBC和ECB两种模式。
